@startuml
class Topology {
    id: String
    components: List
    getComponentsConnectedToNetlistNode(): List<Component>
    getComponentsAsJsonArray(): JsonArray
}

class Components {
    type: String
    id: String
    attributes: Attributes
    netlist: Map
    isConnectedToNetlistNode(): Boolean
    getAsJsonElement(): JsonElement
}

class Attributes {
    name: String
    defaultValue: double
    minValue: double
    maxValue: double
}
Topology "1" *-- "0*" Components : Contains
Components "1" *-- "1" Attributes : Has
@enduml